 ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
 ³    Realm of Kisom by Blazing Fire Software: Bug/Suggestion/Comment Form    ³
 ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ³ Name   : ____________________________ ³ BBS Software : ___________________ ³
 ³ Address: ____________________________ ³ BBS Name     : ___________________ ³
 ³          ____________________________ ³                ___________________ ³
 ³ City   : ____________________________ ³ Multi-Node System : [Yes: _ No: _] ³
 ³ Age    : ___    State / Province : __ ³ Maximum Modem Baud Rate : ________ ³
 ³ Current Version You're Running : ____ ³ FidoNet Address  : _______________ ³
 ³ Your Computer O.S. : ________________ ³ InterNet Address : _______________ ³
 ³ Voice Phone Number : (___) ___ - ____ ³ Your Computer's RAM (Memory) : ___ ³
 ³ B.B.S Phone Number : (___) ___ - ____ ³ Best Time To Call You Voice : ____ ³
 ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ³ (* Please Note - Depending upon the serverity of this form - I may call *) ³
 ³ (* you via VOICE telephone call.   Please fill out the section where it *) ³
 ³ (* says "Best Time To Call You Voice" so that I know just what it says. *) ³
 ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ³ For Bug Reports: Please describe what you were doing, what error was given ³
 ³ and any other information you deem necessary as best as you possibly can : ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ³  For Suggestions/Comments: Please describe where/what the new option will  ³
 ³  be in the game, as well as any comments/information as best as you can :  ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ³ __________________________________________________________________________ ³
 ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
 ³  You can send this form to me via the Postal Service, FileAttach it to me  ³
 ³ in a message on the Internet, File Attach it to me to 1:140/129, or Upload ³
 ³ it to me on my BBS.  All the addresses are given in the ROK Documentation. ³
 ³                                                                            ³
 ³ ** Thank you for filling out this form!   I *ALWAYS* welcome new ideas! ** ³
 ³                                                                            ³
 ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
