@ECHO OFF

IF EXIST "DOORS\LORD.INI" (
  ECHO.
  ECHO PLEASE DELETE THE CONTENTS OF THE RELEASE DIRECTORY AND REBUILD THE SOLUTION
  ECHO BEFORE YOU ATTEMPT TO MAKE A NEW RELEASE
  GOTO END
)

ECHO DELETING UNNECESSARY FILES
DEL X64\SQLITE.INTEROP.DLL
RMDIR X64
DEL X86\SQLITE.INTEROP.DLL
RMDIR X86
DEL MONO.POSIX.DLL
DEL PTY-SHARP.DLL
DEL SYSTEM.DATA.SQLITE.DLL
DEL *.PDB
DEL *.XML

ECHO.
ECHO HIT A KEY TO PACKAGE DOOR-FREE VERSION
PAUSE > NUL
DEL ..\GAMESRV-NODOORS.ZIP
"C:\PROGRAM FILES\7-ZIP\7Z.EXE" a -mx5 -r -tzip -x!_RELEASE.CMD -x!*.VSHOST.EXE -x!DOORS\*.ZIP ..\GameSrv_v_nodoors.zip *.*

ECHO.
ECHO HIT A KEY TO PACKAGE DOOR-FULL VERSION
PAUSE > NUL
CD DOORS
"C:\PROGRAM FILES\7-ZIP\7Z.EXE" x *.zip
DEL *.ZIP
CD ..
DEL ..\GAMESRV.ZIP
"C:\PROGRAM FILES\7-ZIP\7Z.EXE" a -mx5 -r -tzip -x!_RELEASE.CMD -x!*.VSHOST.EXE ..\GameSrv_v.zip *.*

:END

ECHO.
ECHO HIT A KEY TO QUIT
PAUSE > NUL